Update setup script with latest changes

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -17,7 +17,7 @@ provision-project() {
 
 ### DON'T MODIFY ANYTHING BELOW THIS LINE! #####################################
 
-# This setup script was generated with setup_script_generator 0.2.3,
+# This setup script was generated with setup_script_generator 0.4.0,
 # available on RubyGems.
 #
 # To regenerate this section, install the gem and run:
@@ -190,20 +190,25 @@ provision-ruby() {
   USE_BUNDLER_1=0
 
   if [[ -f .tool-versions ]]; then
-    REQUIRED_RUBY_VERSION=$(cat .tool-versions | grep '^ruby ' | sed -Ee 's/^ruby (.+)$/\1/')
+    REQUIRED_RUBY_VERSION=$(cat .tool-versions | grep '^ruby ' | head -n 1 | sed -Ee 's/^ruby (.+)$/\1/')
   elif [[ -f .ruby-version ]]; then
-    REQUIRED_RUBY_VERSION=$(cat .ruby-version)
-  else
-    error "You don't seem to have a Ruby version set in your project."
+    REQUIRED_RUBY_VERSION=$(cat .ruby-version | head -n 1 | sed -Ee 's/^ruby-([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+)$/\1/')
+  fi
+
+  if [[ -z $REQUIRED_RUBY_VERSION ]]; then
+    error "Could not determine required Ruby version for this project."
     print-wrapped "\
-You'll need to create either a .tool-versions file or .ruby-version file in your
-project before you can run this script."
+Your project needs to include either a valid .tool-versions file with a 'ruby'
+line or a valid .ruby-version file."
     exit 1
   fi
 
   ensure-ruby-development-libraries-installed
   ensure-ruby-installed
-  ensure-project-ruby-dependencies-installed
+
+  if [[ -f Gemfile ]]; then
+    ensure-project-ruby-dependencies-installed
+  fi
 }
 
 ensure-ruby-development-libraries-installed() {
@@ -237,10 +242,9 @@ ensure-ruby-installed() {
       fi
     fi
   elif has-executable rvm; then
-    if ! (rvm list | grep $required_ruby_version'\>' &>/dev/null); then
-      banner "Installing Ruby $required_ruby_version with rvm"
-      rvm install $required_ruby_version
-      rvm use $required_ruby_version
+    if ! (rvm list | grep $REQUIRED_RUBY_VERSION'\>' &>/dev/null); then
+      banner "Installing Ruby $REQUIRED_RUBY_VERSION with rvm"
+      rvm install $REQUIRED_RUBY_VERSION
     fi
   else
     error "You don't seem to have a Ruby manager installed."
@@ -261,8 +265,8 @@ has-bundler() {
 ensure-project-ruby-dependencies-installed() {
   banner 'Installing Ruby dependencies'
 
-  if [[ $USE_BUNDLER_1 -eq 1 ]] && (! has-bundler || [[ $(bundle -v) =~ '^1\.' ]]); then
-    gem install bundler -v '~> 1.0'
+  if [[ $USE_BUNDLER_1 -eq 1 ]] && (! has-bundler || ! [[ $(bundle -v) =~ '^Bundler version 1\.' ]]); then
+    gem install bundler:'~> 1.0'
   elif ! has-bundler; then
     gem install bundler
   fi
@@ -272,10 +276,6 @@ ensure-project-ruby-dependencies-installed() {
 
 run-provisions() {
   provision-ruby
-
-  if type provision-project &>/dev/null; then
-    provision-project
-  fi
 }
 
 # --- FIN ----------------------------------------------------------------------
